### ISSUE TITLE
该插件加载报错

### ISSUE THREAD

**Issue by lyu3103** [qwedc001/tesseractOCR_umi_plugin#11]
按照插件库的方式安装后，重启软件显示如下错误：
`win7_x64_TesseractOCR_best_v1.1.0: 动态导入包失败：No module named 'win7_x64_TesseractOCR_best_v1'
`

**Comment by qwedc001** [comment]
请提供您 Umi-OCR/UmiOCR-data/plugins 文件夹结构的截图。
根据描述，初步猜测您将压缩包文件直接放入了文件夹，并没有解压。 如果猜对了我会修改一下readme :-)

**Comment by qwedc001** [comment]
一个正常的插件安装文件夹结构如下
```
plugins
└─ win7_x64_TesseractOCR_best
       ├─ __init__.py **
       ├─ api_tesseractocr.py **
       ├─ i18n.csv **
       ├─ tesseractocr_config.py **
       ├─ engine
       │  └─ tesseractOCR 的核心引擎文件
       └─ site-packages
            └─ tesseractOCR 的依赖库
```

**Comment by lyu3103** [comment]
文件结构是正确的，问题处在解压后的包名上，`win7_x64_TesseractOCR_best_v1.1.0`会被读取为`win7_x64_TesseractOCR_best_v1`，导致检测失败？

**Comment by lyu3103** [comment]
> 文件结构是正确的，问题处在解压后的包名上，`win7_x64_TesseractOCR_best_v1.1.0`会被读取为`win7_x64_TesseractOCR_best_v1`，导致检测失败？

所以我把解压后的文件名的`.`分隔符后面的部分直接删掉，就可以使用了。问题应该跟文件名中的`.`分隔符有关。

**Comment by qwedc001** [comment]
这样啊
我明白了，和python的包名检测模式有关系，下次做压缩包的时候不能加版本号了hhhh
感谢反馈，该issue pin至周末release更新

**Comment by hiroi-sora** [comment]
> `win7_x64_TesseractOCR_best_v1.1.0` 会被读取为 `win7_x64_TesseractOCR_best_v1`，导致检测失败

嗯，这也是我插件加载代码考虑不周，后续会改进插件KEY的设定方式。

当前，用户请手动删除 **插件文件夹名** 中的`.`符号。

**Comment by hiroi-sora** [comment]
@qwedc001 

仓库Release的文件的结构改一下吧。或者从我那下载 [改好的包](https://github.com/hiroi-sora/Umi-OCR_plugins/releases/tag/2.0.0) ，扔到你这边。

我那边的 `win7_x64_TesseractOCR_xxx_v1.1.0.7z` 内部目录结构是正确的。

**Comment by qwedc001** [comment]
好嘞好嘞，这两天忙别的去了忘了重发release了，这就改

**Comment by qwedc001** [comment]
已修改
